package sole.memory.guishop.shop.item;



/**
 * author SoleMemory
 * create by 2017/5/16.
 */
public class ItemName {


    public static String getName(String item){
        switch (item){
            case "1":
                return "石头";
            case "2":
                return "草块";
            case "3":
                return "泥土";
            case "4":
                return "圆石";
            case "5":
                return "橡木木板";
            case "5:1":
                return "云杉木板";
            case "5:2":
                return "桦木木板";
            case "5:3":
                return "丛林木板";
            case "6":
                return "橡树树苗";
            case "6:1":
                return "云杉树苗";
            case "6:2":
                return "桦木树苗";
            case "6:3":
                return "丛林树苗";
            case "12":
                return "沙子";
            case "13":
                return "沙硕";
            case "14":
                return "金矿石";
            case "15":
                return "铁矿石";
            case "16":
                return "煤矿石";
            case "17":
                return "橡木";
            case "17:1":
                return "云杉木";
            case "17:2":
                return "白桦木 ";
            case "17:3":
                return "丛林木";
            case "18":
                return "橡木树叶";
            case "18:1":
                return "云杉树叶";
            case "18:2":
                return "白桦树叶";
            case "18:3":
                return "丛林树叶";
            case "20":
                return "玻璃";
            case "21":
                return "青金石矿石";
            case "22":
                return "青金石块";
            case "23":
                return "发射器";
            case "24":
                return "沙石";
            case "24:1":
                return "錾制沙石";
            case "24:2":
                return "平滑沙石";
            case "25":
                return "音符盒";
            case "27":
                return "动力铁轨";
            case "28":
                return "探测铁轨";
            case "29":
                return "粘性活塞";
            case "31":
                return "灌木";
            case "32":
                return "枯死的灌木";
            case "33":
                return "活塞";
            case "35":
                return "白色羊毛";
            case "35:1":
                return "橙色羊毛";
            case "35:2":
                return "红色羊毛";
            case "35:3":
                return "蓝色羊毛";
            case "35:4":
                return "黄色羊毛";
            case "35:5":
                return "灰色羊毛";
            case "35:6":
                return "粉色羊毛";
            case "35:7":
                return "灰色羊毛";
            case "35:8":
                return "淡灰色羊毛";
            case "35:9":
                return "青色羊毛";
            case "35:10":
                return "紫色羊毛";
            case "35:11":
                return "蓝色羊毛";
            case "35:12":
                return "棕色羊毛";
            case "35:13":
                return "深绿色羊毛";
            case "35:14":
                return "红色羊毛";
            case "35:15":
                return "黑色羊毛";
            case "37":
                return "蒲公英";
            case "38":
                return "玫瑰";
            case "39":
                return "棕色蘑菇";
            case "40":
                return "红色蘑菇";
            case "41":
                return "金块";
            case "42":
                return "铁块";
            case "44":
                return "石台阶";
            case "44:1":
                return "沙石台阶";
            case "44:2":
                return "木台阶";
            case "44:3":
                return "圆石台阶";
            case "44:4":
                return "砖台阶";
            case "44:5":
                return "石砖台阶";
            case "45":
                return "红砖";
            case "46":
                return "TNT";
            case "47":
                return "书架";
            case "48":
                return "苔石";
            case "49":
                return "黑曜石";
            case "50":
                return "火把";
            case "53":
                return "橡木楼梯";
            case "54":
                return "箱子";
            case "56":
                return "钻石矿石";
            case "57":
                return "钻石块";
            case "58":
                return "工作台";
            case "61":
                return "熔炉";
            case "65":
                return "梯子";
            case "66":
                return "铁轨";
            case "67":
                return "石楼梯";
            case "69":
                return "拉杆";
            case "70":
                return "石压力板";
            case "72":
                return "木压力板";
            case "73":
                return "红石矿石";
            case "76":
                return "红石火把";
            case "77":
                return "石按钮";
            case "79":
                return "冰";
            case "80":
                return "雪";
            case "81":
                return "仙人掌";
            case "82":
                return "粘土";
            case "84":
                return "唱片机";
            case "85":
                return "栅栏";
            case "86":
                return "南瓜";
            case "87":
                return "地狱岩";
            case "88":
                return "灵魂沙";
            case "89":
                return "萤石";
            case "91":
                return "南瓜灯";
            case "96":
                return "活板门";
            case "98":
                return "石砖";
            case "98:1":
                return "苔石砖";
            case "98:2":
                return "裂石砖";
            case "98:3":
                return "錾制石砖";
            case "99":
                return "蘑菇";
            case "100":
                return "蘑菇";
            case "101":
                return "铁栅栏";
            case "102":
                return "玻璃板";
            case "103":
                return "西瓜";
            case "106":
                return "藤蔓";
            case "107":
                return "栅栏门";
            case "108":
                return "砖楼梯";
            case "109":
                return "石楼梯";
            case "112":
                return "地狱砖块";
            case "113":
                return "地狱砖栅栏";
            case "114":
                return "地狱砖楼梯";
            case "116":
                return "附魔台";
            case "121":
                return "末地石";
            case "122":
                return "龙蛋";
            case "123":
                return "红石灯";
            case "126":
                return "橡木台阶";
            case "126:1":
                return "云杉台阶";
            case "126:2":
                return "桦木台阶";
            case "126:3":
                return "丛林台阶";
            case "128":
                return "沙石楼梯";
            case "129":
                return "绿宝石矿石";
            case "130":
                return "末影箱";
            case "133":
                return "绿宝石矿石";
            case "134":
                return "云杉木楼梯";
            case "135":
                return "桦木楼梯";
            case "136":
                return "丛林木楼梯";
            case "159":
                return "黏土";
            case "159:1":
                return "橙色黏土";
            case "159:2":
                return "黏土";
            case "159:3":
                return "黏土";
            case "159:4":
                return "黏土";
            case "159:5":
                return "黏土";
            case "159:6":
                return "黏土";
            case "159:7":
                return "黏土";
            case "159:8":
                return "黏土";
            case "159:9":
                return "黏土";
            case "159:10":
                return "黏土";
            case "159:11":
                return "黏土";
            case "159:12":
                return "黏土";
            case "159:13":
                return "黏土";
            case "159:14":
                return "黏土";
            case "138":
                return "信标";
            case "139":
                return "圆石围栏";
            case "139:1":
                return "苔石围栏";
            case "147":
                return "黄金踏板";
            case "148":
                return "铁踏板";
            case "151":
                return "红石灯";
            case "152":
                return "红石块";
            case "153":
                return "石英矿";
            case "155":
                return "石英块";
            case "155:1":
                return "熬制石英块";
            case "155:2":
                return "竖纹石英块";
            case "156":
                return "石英台阶";
            case "256":
                return "铁铲子";
            case "257":
                return "铁镐";
            case "258":
                return "铁斧";
            case "259":
                return "打火石";
            case "261":
                return "弓";
            case "267":
                return "铁剑";
            case "268":
                return "木剑";
            case "269":
                return "木铲";
            case "270":
                return "木镐";
            case "271":
                return "木斧";
            case "272":
                return "石剑";
            case "273":
                return "石铲";
            case "274":
                return "石镐";
            case "275":
                return "石斧";
            case "283":
                return "金剑";
            case "284":
                return "金铲";
            case "285":
                return "金镐";
            case "286":
                return "金斧";
            case "290":
                return "木锄";
            case "291":
                return "石锄";
            case "292":
                return "铁锄";
            case "293":
                return "钻石锄";
            case "294":
                return "金锄";
            case "276":
                return "钻石剑";
            case "277":
                return "钻石铲";
            case "278":
                return "钻石镐";
            case "279":
                return "钻石斧";
            case "325":
                return "桶";
            case "326":
                return "水桶";
            case "327":
                return "岩浆桶";
            case "345":
                return "指南针";
            case "346":
                return "钓鱼竿";
            case "347":
                return "钟";
            case "359":
                return "剪刀";
            case "260":
                return "苹果";
            case "281":
                return "碗";
            case "282":
                return "炖蘑菇";
            case "295":
                return "小麦种子";
            case "296":
                return "小麦";
            case "297":
                return "面包";
            case "319":
                return "生猪排";
            case "320":
                return "熟猪排";
            case "322":
                return "金苹果";
            case "335":
                return "牛奶";
            case "349":
                return "生鱼";
            case "350":
                return "熟鱼";
            case "353":
                return "糖";
            case "354":
                return "蛋糕";
            case "357":
                return "曲奇";
            case "360":
                return "西瓜";
            case "361":
                return "南瓜种子";
            case "362":
                return "西瓜种子";
            case "363":
                return "生牛肉";
            case "364":
                return "牛排";
            case "365":
                return "生鸡肉";
            case "366":
                return "熟鸡肉";
            case "298":
                return "皮革帽子";
            case "299":
                return "皮革外衣";
            case "300":
                return "皮革裤子";
            case "301":
                return "皮靴";
            case "306":
                return "铁头盔";
            case "307":
                return "铁盔甲";
            case "308":
                return "铁护腿";
            case "309":
                return "铁靴";
            case "310":
                return "钻石头盔";
            case "311":
                return "钻石胸甲";
            case "312":
                return "钻石护腿";
            case "313":
                return "钻石靴";
            case "314":
                return "金头盔";
            case "315":
                return "金护甲";
            case "316":
                return "金护腿";
            case "317":
                return "金靴子";
            case "263":
                return "煤炭";
            case "263:1":
                return "木炭";
            case "264":
                return "钻石";
            case "265":
                return "铁锭";
            case "266":
                return "金锭";
            case "315:4":
                return "青金石";
            case "348":
                return "萤石粉";
            case "373":
                return "水瓶";
            case "370":
                return "恶魂之泪";
            case "371":
                return "金粒";
            case "372":
                return "地狱庞";
            case "374":
                return "玻璃瓶";
            case "375":
                return "蜘蛛眼";
            case "376":
                return "发酵的蜘蛛眼";
            case "377":
                return "烈焰粉";
            case "378":
                return "岩浆膏";
            case "381":
                return "末影之眼";
            case "382":
                return "闪烁的西瓜";
            case "321":
                return "画";
            case "323":
                return "告示牌";
            case "324":
                return "木门";
            case "330":
                return "铁门";
            case "336":
                return "红砖";
            case "337":
                return "粘土";
            case "355":
                return "床";
            case "379":
                return "酿造台";
            case "380":
                return "炼药锅";
            case "388":
                return "绿宝石";
            case "351":
                return "墨囊";
            case "351:1":
                return "红色玫瑰";
            case "351:2":
                return "仙人掌绿";
            case "351:3":
                return "可可豆";
            case "351:4":
                return "青金石";
            case "351:5":
                return "紫色的染料";
            case "351:6":
                return "青色的染料";
            case "351:7":
                return "浅灰色的染料";
            case "351:8":
                return "灰色的染料";
            case "351:9":
                return "粉红色染料";
            case "351:10":
                return "黄绿色染料";
            case "351:11":
                return "蒲公英黄";
            case "351:12":
                return "浅蓝色的染料";
            case "351:13":
                return "品红染料";
            case "351:14":
                return "橙色染料";
            case "351:15":
                return "骨粉";
            case "262":
                return "箭";
            case "280":
                return "木棍";
            case "287":
                return "线";
            case "288":
                return "羽毛";
            case "289":
                return "火药";
            case "318":
                return "燧石";
            case "332":
                return "雪球";
            case "334":
                return "皮革";
            case "338":
                return "甘蔗";
            case "339":
                return "纸";
            case "340":
                return "书";
            case "341":
                return "粘液球";
            case "344":
                return "鸡蛋";
            case "352":
                return "骨头";
            case "367":
                return "腐肉";
            case "368":
                return "末影珍珠";
            case "369":
                return "火焰棒";
           default:
               return "不存在此物品";
        }
    }

}
